package com.br.domain.model.enums;

public enum TypeMovement{
	    CRIACAO(0, "CRIACAO"),
	    ANEXACAO(1, "Anexação"),
	    TRANSFERENCIA(2, "Transferência"),
	    RECEBIMENTO(3, "Recebimento"),
	    DESPACHO(4, "Despacho"),
	    DESPACHO_TRANSFERENCIA(5, "Despacho com Transferência"),
	    DESPACHO_INTERNO(6, "Despacho Interno"),
	    DESPACHO_INTERNO_TRANSFERENCIA(7, "Despacho Interno com Transferência"),
	    ARQUIVAMENTO_CORRENTE(8, "Arquivamento Corrente"),
	    ELIMINACAO(9, "Eliminação"),
	    ASSINATURA_DIGITAL_DOCUMENTO(10, "Assinatura"),
	    JUNTADA(11, "Juntada"),
	    JUNTADA_EXTERNO(12, "Desentranhamento"),
	    CANCELAMENTO_JUNTADA(13, "Desentranhamento"),
	    CANCELAMENTO_DE_MOVIMENTACAO(14, "Cancelamento de Movimentação"),
	    EXTRAVIO(15, "Extravio"),
	    REFERENCIA(16, "Vinculação"),
	    TRANSFERENCIA_EXTERNA(17, "Transferência Externa"),
	    DESPACHO_TRANSFERENCIA_EXTERNA(18, "Despacho com Transferência Externa"),
	    ARQUIVAMENTO_PERMANENTE(19, "Recolhimento ao Arq. Permanente"),
	    ARQUIVAMENTO_INTERMEDIARIO(20, "Arquivamento Intermediário"),
	    DESARQUIVAMENTO_CORRENTE(21, "Desarquivamento"),
	    ASSINATURA_DIGITAL_MOVIMENTACAO(22, "Assinatura de Movimentação"),
	    RECEBIMENTO_TRANSITORIO(23, "Recebimento Transitório"),
	    INCLUSAO_DE_COSIGNATARIO(24, "Inclusão de Cossignatário"),
	    REGISTRO_ASSINATURA_DOCUMENTO(25, "Registro de Assinatura"),
	    REGISTRO_ASSINATURA_MOVIMENTACAO(26, "Registro de Assinatura de Movimentação"),
	    ATUALIZACAO(27, "Atualização"),
	    ANOTACAO(28, "Anotação"),
	    REDEFINICAO_NIVEL_ACESSO(29, "Redefinição de Sigilo"),
	    REGISTRO_ACESSO_INDEVIDO(30, "Registro de Acesso Alheio"),
	    JUNTADA_A_DOCUMENTO_EXTERNO(31, "Juntada a Documento Externo"),
	    AGENDAMENTO_DE_PUBLICACAO(32, "Agendamento de Publicação no DJE"),
	    REMESSA_PARA_PUBLICACAO(33, "Remessa para Publicação"),
	    CONFIRMACAO_DE_REMESSA_MANUAL(34, "Confirmação de Remessa Manual"),
	    DISPONIBILIZACAO(35, "Disponibilização"),
	    AGENDAMENTO_DE_PUBLICACAO_BOLETIM(36, "Solicitação de Publicação no Boletim"),
	    PUBLICACAO_BOLETIM(37, "Publicação do Boletim"),
	    PEDIDO_PUBLICACAO(38, "Pedido de Publicação no DJE"),
	    NOTIFICACAO_PUBL_BI(39, "Notificação de Publicação no Boletim"),
	    APENSACAO(40, "Apensação"),
	    DESAPENSACAO(41, "Desapensação"),
	    ENCERRAMENTO_DE_VOLUME(42, "Encerramento de Volume"),
	    VINCULACAO_PAPEL(43, "Definição de Perfil"),
	    CONFERENCIA_COPIA_DOCUMENTO(44, "Autenticação de Documento"),
	    SOBRESTAR(45, "Sobrestar"),
	    DESOBRESTAR(46, "Dessobrestar"),
	    TORNAR_SEM_EFEITO(47, "Tornar sem Efeito"),
	    INDICACAO_GUARDA_PERMANENTE(48, "Indicação para Guarda Permanente"),
	    REVERSAO_INDICACAO_GUARDA_PERMANENTE(49, "Reversão de Ind. para Guarda Permanente"),
	    RECLASSIFICACAO(50, "Reclassificação"),
	    AVALIACAO(51, "Avaliação"),
	    AVALIACAO_COM_RECLASSIFICACAO(52, "Avaliação com Reclassificação"),
	    INCLUSAO_EM_EDITAL_DE_ELIMINACAO(53, "Inclusão em Edital de Eliminação"),
	    RETIRADA_DE_EDITAL_DE_ELIMINACAO(54, "Retirada de Edital de Eliminação"),
	    DESARQUIVAMENTO_INTERMEDIARIO(55, "Desarquivamento Intermediário"),
	    PENDENCIA_DE_ANEXACAO(56, "Pendência de Anexação"),
	    ASSINATURA_COM_SENHA(57, "Assinatura com senha"),
	    ASSINATURA_MOVIMENTACAO_COM_SENHA(58, "Assinatura de movimentação com senha"),
	    CONFERENCIA_COPIA_COM_SENHA(59, "Autenticação de Documento com senha"),
	    CONTROLE_DE_COLABORACAO(60, "Controle de Coloboração"),
	    MARCACAO(61, "Marcação"),
	    COPIA(62, "Inclusão de Cópia"),
	    ANEXACAO_DE_ARQUIVO_AUXILIAR(63, "Anexação de Arquivo Auxiliar"),
	    SOLICITACAO_DE_ASSINATURA(64, "Solicitação de Assinatura"),
	    CIENCIA(65, "Tomar Ciência"),
	    AUTUAR(66, "Autuação"),
	    RESTRINGIR_ACESSO(67, "Restringir Acesso"),
	    REFAZER(68, "Refazer Documento"),
	    ASSINATURA_POR(69, "Assinatura \"por\""),
	    GERAR_PROTOCOLO(70, "Gerar Protocolo"),
	    SUBSTITUICAO_RESPONSAVEL(71, "Substituição de Responsável"),
	    REORDENACAO_DOCUMENTO(72, "Reordenar"),
	    ORDENACAO_ORIGINAL_DOCUMENTO(73, "Ordenar"),
	    PUBLICACAO_PORTAL_TRANSPARENCIA(74, "Publicação no Portal da Transparência"),
	    EXIBIR_NO_ACOMPANHAMENTO_DO_PROTOCOLO(75, "Disponibilizar no Acompanhamento do Protocolo"),
	    PRAZO_ASSINATURA(76, "Prazo para Assinatura"),
	    TRAMITE_PARALELO(77, "Trâmite Paralelo"),
	    NOTIFICACAO(78, "Notificação"),
	    CONCLUSAO(79, "Conclusão de Trâmite"),
	    ENVIO_SIAFEM(80, "Envio ao SIAFEM"),
	    GERAR_LINK_PUBLICO_PROCESSO(81, "Gerar link público do Processo"),
	    ENVIO_PARA_VISUALIZACAO_EXTERNA(82, "Envio para visualização externa"),
	    AGENDAR_PUBLICACAO_DOE(83, "Agendar Publicação DOE"),
	    ENVIAR_PUBLICACAO_DOE(84, "Enviar Publicação DOE"),
	    ORDEM_ASSINATURA(85, "Ordem de Assinatura"),
	    CANCELAR_PUBLICACAO_DOE(86, "Cancelar Publicação DOE");

	private final int id;
	private final String descr;

	TypeMovement(int id, String descr) {
		this.id = id;
		this.descr = descr;
	}

	public int getId() {
		return id;
	}
}
